function groupAcc = plot_group_acc(cells,poststrat,plotResults,exitPollData)
    %% Initialize    
    groupDemo = {{'ideology','sex'},{'ideology','party'},{'sex','party'},...
        {'sex','ideology'},{'race','ideology'},{'race','party'},...
        {'race','party'},{'sex','party'},{'sex','party'},...
        {'party','education'},{'sex','age'},{'sex','education'},...
        {'race','age'},{'sex','age'},{'race','education'},...
        {'sex','education'},{'ideology','party'},{'sex','education'},...
        {'sex','party'},{'sex','ideology'},{'race','sex'},...
        {'race','education'},{'race','sex'},{'ideology','education'},...
        {'race','ideology'},{'sex','ideology'},{'race','party'},...
        {'race','ideology'}};
    groupCat = {{'conservative','male'},{'conservative','republican'},{'male','republican'},...
        {'female','conservative'},{'white','conservative'},{'white','republican'},...
        {'white','democrat'},{'female','republican'},{'female','democrat'}...
        {'democrat','college graduate'},{'male','45-64'},{'male','college graduate'},...
        {'white','30-44'},{'female','45-64'},{'white','some college'},...
        {'female','some college'},{'liberal','democrat'},{'female','college graduate'}...
        {'male','other'},{'male','moderate'},{'white','male'},...
        {'white','college graduate'},{'white','female'},{'moderate','college graduate'},...
        {'white','liberal'},{'female','moderate'},{'white','other'},...
        {'white','moderate'}};
    
    assert(length(groupDemo) == length(groupCat));
    numGroups = length(groupDemo);
    
    groupNames = cell(numGroups,1);
    
    %% Get accuracies for each group
    groupAcc = zeros(numGroups,1);
    for g=1:numGroups
        groupNames{g} = strjoin(groupCat{g});
        groupAcc(g) = get_acc(cells,groupDemo{g},groupCat{g},poststrat,exitPollData);
    end
    
    %% Plot results
    if plotResults
        xaxis = 1:length(groupAcc);
        zeroMark = 0*xaxis;
        plot(zeroMark,xaxis,'--')
        hold on;
        plot(groupAcc,xaxis,'o')
        set(gca, 'YTick',1:length(groupAcc), 'YTickLabel', groupNames)
    end
    
    %% Take absolute value
    groupAcc = abs(groupAcc);
end

